using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using AutoGeneratedWebApplication.Models;

namespace AutoGeneratedWebApplication.Data
{
    public class AutoGeneratedWebApplicationContext : DbContext
    {
        public AutoGeneratedWebApplicationContext (DbContextOptions<AutoGeneratedWebApplicationContext> options)
            : base(options)
        {
        }

        public DbSet<AutoGeneratedWebApplication.Models.Product> Product { get; set; }
    }
}
