using System.ComponentModel.DataAnnotations;

namespace AutoGeneratedWebApplication.Models
{
    public class Product
    {
        public int ProductID { get; set; }
        [Required]
        public string Name { get; set; }
        [Range(100,100000)]
        public int Cost { get; set; }
        public string Brand { get; set; }
    }
}
