// <auto-generated />
using System;
using KnowledgeHubPortal.MVCWebApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KnowledgeHubPortal.MVCWebApplication.Migrations
{
    [DbContext(typeof(KnowledgeHubDbContext))]
    [Migration("20220401061858_articles")]
    partial class articles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KnowledgeHubPortal.MVCWebApplication.Models.Article", b =>
                {
                    b.Property<int>("ArticleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArticleUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CatagoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateSubmited")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("SubmittedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArticleID");

                    b.HasIndex("CatagoryID");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("KnowledgeHubPortal.MVCWebApplication.Models.Catagory", b =>
                {
                    b.Property<int>("CatagoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CatagoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CatagoryID");

                    b.ToTable("Catagories");

                    b.HasData(
                        new
                        {
                            CatagoryID = 111,
                            CatagoryName = "Education",
                            Description = "Its good for childerns"
                        },
                        new
                        {
                            CatagoryID = 222,
                            CatagoryName = "Technology",
                            Description = "All the latest technologies of computer science"
                        },
                        new
                        {
                            CatagoryID = 333,
                            CatagoryName = "Entertinment",
                            Description = "Better way of passing time"
                        },
                        new
                        {
                            CatagoryID = 444,
                            CatagoryName = "Social",
                            Description = "Get a social network"
                        });
                });

            modelBuilder.Entity("KnowledgeHubPortal.MVCWebApplication.Models.Article", b =>
                {
                    b.HasOne("KnowledgeHubPortal.MVCWebApplication.Models.Catagory", "Catagory")
                        .WithMany()
                        .HasForeignKey("CatagoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catagory");
                });
#pragma warning restore 612, 618
        }
    }
}
